In [1]:
import sqlite3
conn = sqlite3.connect('PokemonDB.db')
c = conn.cursor()

In [2]:
import pandas as pd
csv_df = pd.read_csv("C:\\Users\\Gabe\\Documents\\Bellevue University\\Data Preparation\\Final Project\\Data for Pokemon Database\\PokemonCSV.csv")
website_df = pd.read_csv("C:\\Users\\Gabe\\Documents\\Bellevue University\\Data Preparation\\Final Project\\Data for Pokemon Database\\PokemonWebsite.csv")
api_df = pd.read_csv("C:\\Users\\Gabe\\Documents\\Bellevue University\\Data Preparation\\Final Project\\Data for Pokemon Database\\PokemonAPI.csv")

In [3]:
csv_df.to_sql("CSV", conn, if_exists='replace', index=False)
pd.read_sql('select * from CSV', conn)

,name,pokedex_number,percentage_male,type1,type2,classification,capture_rate,base_egg_steps,abilities,experience_growth,...,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water
0,Bulbasaur,1,88.1,grass,poison,Seed,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
1,Ivysaur,2,88.1,grass,poison,Seed,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
2,Venusaur,3,88.1,grass,poison,Seed,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
3,Charmander,4,88.1,fire,No Secondary Type,Lizard,45,5120,"['Blaze', 'Solar Power']",1059860,...,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0
4,Charmeleon,5,88.1,fire,No Secondary Type,Flame,45,5120,"['Blaze', 'Solar Power']",1059860,...,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,Celesteela,797,50.0,steel,flying,Launch,25,30720,['Beast Boost'],1250000,...,1.0,0.25,0.0,1.0,0.5,0.0,0.5,1.0,0.5,1.0
797,Kartana,798,50.0,grass,steel,Drawn Sword,255,30720,['Beast Boost'],1250000,...,1.0,0.25,1.0,1.0,0.5,0.0,0.5,0.5,0.5,0.5
798,Guzzlord,799,50.0,dark,dragon,Junkivore,15,30720,['Beast Boost'],1250000,...,0.5,0.50,1.0,2.0,1.0,1.0,0.0,1.0,1.0,0.5
799,Necrozma,800,50.0,psychic,No Secondary Type,Prism,3,30720,['Prism Armor'],1250000,...,2.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0
800,Magearna,801,50.0,steel,fairy,Artificial,3,30720,['Soul-Heart'],1250000,...,1.0,0.50,2.0,0.5,0.5,0.0,0.5,0.5,1.0,1.0

In [4]:
website_df.to_sql("WEBSITE", conn, if_exists='replace', index=False)
pd.read_sql('select * from WEBSITE', conn)

,pokedex_number,name,hp,attack,defense,sp_attack,sp_defense,speed,type1,type2
0,1,Bulbasaur,45,49,49,65,65,45,Grass,Poison
1,2,Ivysaur,60,62,63,80,80,60,Grass,Poison
2,3,Venusaur,80,82,83,100,100,80,Grass,Poison
3,4,Charmander,39,52,43,60,50,65,Fire,No Secondary Type
4,5,Charmeleon,58,64,58,80,65,80,Fire,No Secondary Type
...,...,...,...,...,...,...,...,...,...,...
796,796,Xurkitree,83,89,71,173,71,83,Electric,No Secondary Type
797,797,Celesteela,97,101,103,107,101,61,Steel,Flying
798,798,Kartana,59,181,131,59,31,109,Grass,Steel
799,799,Guzzlord,223,101,53,97,53,43,Dark,Dragon
800,800,Necrozma,97,107,101,127,89,79,Psychic,No Secondary Type

In [5]:
api_df.to_sql("API", conn, if_exists='replace', index=False)
pd.read_sql('select * from API', conn)

,pokedex_number,name,type1,type2,base_experience,abilities,moves
0,62,poliwrath,fighting,water,230,"['swift-swim', 'damp', 'water-absorb']","['double-slap', 'mega-punch', 'ice-punch', 'me..."

In [12]:
csv_website_df = csv_df.merge(website_df, on=['pokedex_number', 'name', 'type1', 'type2', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed'], how='left')
csv_website_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 801 entries, 0 to 800
Data columns (total 37 columns):
name                 801 non-null object
pokedex_number       801 non-null int64
percentage_male      801 non-null float64
type1                801 non-null object
type2                801 non-null object
classification       801 non-null object
capture_rate         801 non-null int64
base_egg_steps       801 non-null int64
abilities            801 non-null object
experience_growth    801 non-null int64
base_happiness       801 non-null int64
hp                   801 non-null int64
attack               801 non-null int64
defense              801 non-null int64
sp_attack            801 non-null int64
sp_defense           801 non-null int64
speed                801 non-null int64
generation           801 non-null int64
is_legendary         801 non-null int64
against_bug          801 non-null float64
against_dark         801 non-null float64
against_dragon       801 non-null float64
against_electric     801 non-null float64
against_fairy        801 non-null float64
against_fight        801 non-null float64
against_fire         801 non-null float64
against_flying       801 non-null float64
against_ghost        801 non-null float64
against_grass        801 non-null float64
against_ground       801 non-null float64
against_ice          801 non-null float64
against_normal       801 non-null float64
against_poison       801 non-null float64
against_psychic      801 non-null float64
against_rock         801 non-null float64
against_steel        801 non-null float64
against_water        801 non-null float64
dtypes: float64(19), int64(13), object(5)
memory usage: 237.8+ KB