In [66]:
# Libraries and import data file
import pandas as pd
df = pd.read_csv("C:\\Users\\Gabe\\Documents\\Bellevue University\\Data Preparation\\Final Project\\Data\\pokemon.csv")
df.head(10)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
5,"['Blaze', 'Solar Power']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,88.1,6,159,115,100,fire,flying,90.5,1,0
6,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,NaN,9.0,1,0
7,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,8,65,80,58,water,NaN,22.5,1,0
8,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0
9,"['Shield Dust', 'Run Away']",1.00,1.0,1.0,1.0,1.0,0.5,2.0,2.0,1.0,...,50.0,10,20,20,45,bug,NaN,2.9,1,0

In [67]:
# Replace Headers
df.rename(columns={"classfication": "classification"}, inplace = True)

In [68]:
# Null & Empty Values

# Context:

# Type 2:
# Not all Pokemon will have a secondary type, but there are many Pokemon
# that do. Therefore, you cannot remove ones that only have one or 
# remove the column containing the secondary type because it gives more
# details about the creature. 

# Percentage Male:
# Many pokemon have the chance of either being male or female. However, not
# all pokemon can be classified within a gender of male or female. 
# Therefore, I will give all of these special cases a 50% chance of being 
# either male or female


print("Sum of Null Values")
print(df.isnull().sum())

print("Sum of Empty Values")
print(df.isnull().sum().sum())

# Type 2
# Replace the blank values with "No Secondary Type"
df['type2'].fillna("No Secondary Type", inplace=True)

# Percentage Male
# Replace the blank values with 50
df['percentage_male'].fillna(50, inplace=True)

# Remove hieght and weight of Pokemon since blank values and no need for 
# Japanese name
df.drop(["height_m", "weight_kg", "japanese_name"], axis=1, inplace=True)

Sum of Null Values
abilities              0
against_bug            0
against_dark           0
against_dragon         0
against_electric       0
against_fairy          0
against_fight          0
against_fire           0
against_flying         0
against_ghost          0
against_grass          0
against_ground         0
against_ice            0
against_normal         0
against_poison         0
against_psychic        0
against_rock           0
against_steel          0
against_water          0
attack                 0
base_egg_steps         0
base_happiness         0
base_total             0
capture_rate           0
classification         0
defense                0
experience_growth      0
height_m              20
hp                     0
japanese_name          0
name                   0
percentage_male       98
pokedex_number         0
sp_attack              0
sp_defense             0
speed                  0
type1                  0
type2                384
weight_kg             20
generation             0
is_legendary           0
dtype: int64
Sum of Empty Values
522

In [69]:
# Change Data Types
df.info()
df.astype({"capture_rate": 'int64'})

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 38 columns):
abilities            801 non-null object
against_bug          801 non-null float64
against_dark         801 non-null float64
against_dragon       801 non-null float64
against_electric     801 non-null float64
against_fairy        801 non-null float64
against_fight        801 non-null float64
against_fire         801 non-null float64
against_flying       801 non-null float64
against_ghost        801 non-null float64
against_grass        801 non-null float64
against_ground       801 non-null float64
against_ice          801 non-null float64
against_normal       801 non-null float64
against_poison       801 non-null float64
against_psychic      801 non-null float64
against_rock         801 non-null float64
against_steel        801 non-null float64
against_water        801 non-null float64
attack               801 non-null int64
base_egg_steps       801 non-null int64
base_happiness       801 non-null int64
base_total           801 non-null int64
capture_rate         801 non-null int64
classification       801 non-null object
defense              801 non-null int64
experience_growth    801 non-null int64
hp                   801 non-null int64
name                 801 non-null object
percentage_male      801 non-null float64
pokedex_number       801 non-null int64
sp_attack            801 non-null int64
sp_defense           801 non-null int64
speed                801 non-null int64
type1                801 non-null object
type2                801 non-null object
generation           801 non-null int64
is_legendary         801 non-null int64
dtypes: float64(19), int64(14), object(5)
memory usage: 237.9+ KB

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,name,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Bulbasaur,88.1,1,65,65,45,grass,poison,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Ivysaur,88.1,2,80,80,60,grass,poison,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Venusaur,88.1,3,122,120,80,grass,poison,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,Charmander,88.1,4,60,50,65,fire,No Secondary Type,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,Charmeleon,88.1,5,80,65,80,fire,No Secondary Type,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,Celesteela,50.0,797,107,101,61,steel,flying,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,Kartana,50.0,798,59,31,109,grass,steel,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,Guzzlord,50.0,799,97,53,43,dark,dragon,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,Necrozma,50.0,800,127,89,79,psychic,No Secondary Type,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,Magearna,50.0,801,130,115,65,steel,fairy,7,1

In [70]:
# Readable format
df = df[["name", "pokedex_number", "percentage_male", "type1", "type2", "classification", "capture_rate", "base_egg_steps", "abilities", "experience_growth", "base_happiness", "hp", "attack", "defense", "sp_attack", "sp_defense", "speed", "generation", "is_legendary", "against_bug","against_dark","against_dragon","against_electric","against_fairy","against_fight","against_fire","against_flying","against_ghost","against_grass","against_ground","against_ice","against_normal","against_poison","against_psychic","against_rock","against_steel","against_water"]]
df.head()

,name,pokedex_number,percentage_male,type1,type2,classification,capture_rate,base_egg_steps,abilities,experience_growth,...,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water
0,Bulbasaur,1,88.1,grass,poison,Seed PokÃ©mon,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
1,Ivysaur,2,88.1,grass,poison,Seed PokÃ©mon,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
2,Venusaur,3,88.1,grass,poison,Seed PokÃ©mon,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
3,Charmander,4,88.1,fire,No Secondary Type,Lizard PokÃ©mon,45,5120,"['Blaze', 'Solar Power']",1059860,...,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0
4,Charmeleon,5,88.1,fire,No Secondary Type,Flame PokÃ©mon,45,5120,"['Blaze', 'Solar Power']",1059860,...,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0

In [72]:
# Remove duplicates
df['classification']=df['classification'].str.replace('PokÃ©mon', "")
df.head()

,name,pokedex_number,percentage_male,type1,type2,classification,capture_rate,base_egg_steps,abilities,experience_growth,...,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water
0,Bulbasaur,1,88.1,grass,poison,Seed,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
1,Ivysaur,2,88.1,grass,poison,Seed,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
2,Venusaur,3,88.1,grass,poison,Seed,45,5120,"['Overgrow', 'Chlorophyll']",1059860,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
3,Charmander,4,88.1,fire,No Secondary Type,Lizard,45,5120,"['Blaze', 'Solar Power']",1059860,...,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0
4,Charmeleon,5,88.1,fire,No Secondary Type,Flame,45,5120,"['Blaze', 'Solar Power']",1059860,...,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0